### PR TITLE
copy icon-api.md from public site repo

### PR DESCRIPTION
**Pull request by cstrnt**
**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
Bug fix

**What is the current behavior? (You can also link to an open issue here)**

The `autocomplete/icon-api` site is 404

**What is the new behavior (if this is a feature change)?**

The site exists again

**Additional info:**

### CODE REVIEW

**Comment by falky97** [comment]
@mattschrage Can you check this?

**Review by mattschrage — APPROVED** [review]
👍

**Comment by mattschrage** [comment]
It seems like the icon API is live? https://withfig.com/docs/autocomplete/reference/icon-api

**Comment by cstrnt** [comment]
I think you did a merge into main shortly after I created the PR, so we can just close it

**Pull request closed without merging**
